### ISSUE TITLE
Using DGCNN for nodes with multidimensional attributes

### ISSUE THREAD

**Issue by wangc94** [muhanzhang/pytorch_DGCNN#1]
Hi~
I'm trying to follow your work and using it for weather forecasting. The nodes in my dataset has multidimensional attributes. And I had saw **DGCNN** can work for it in you paper. But I couldn't find this procedure and the data format in you code. Also in the datasets which you provided in this **pytorch_DGCNN**, the nodes only has the tag rather than multidimensional attributes. Do I need to write the multidimensional attributes procedure  code myself?

**Comment by muhanzhang** [comment]
Hi~ For this pytorch_DGCNN, it does not support multi-dimensional attributes currently, but it should not be hard to extend this function. My original implementation of DGCNN in Torch directly supports multi-dimensional attributes, which is here: https://github.com/muhanzhang/DGCNN. You may have a try first. You need to process your data into: dataset = {instance={i: {1: A_i, 2: X_i}}, label={i: label_i}} format, where X_i denotes the attribute matrix of the ith graph. Then, specify "-nodeLabel original" when you run "th main.lua ..." to directly use the attribute matrices as node features. 

Let me know if you have difficulties transforming the data.

**Comment by muhanzhang** [comment]
Hello, please check the new version for the support of multi-dimensional continuous node features.
