### ISSUE TITLE
How to use Synthie?

### ISSUE THREAD

**Issue by fermat97** [muhanzhang/pytorch_DGCNN#12]
Hi, to use Synthie dataset , is it enough to change the dataset name in run_DGCNN.sh to Synthie? I am a bit confused.

**Comment by fermat97** [comment]
My question is, how do the code benefit from other files such as 

> Synthie_graph_indicator.txt
> Synthie_graph_labels.txt
> Synthie_node_attributes.txt
> Synthie_A.txt

Since I have discarded those files and the code still works with only Synthie.txt file. That is why I am confused, since you have written the data should be in this specific format but it seems that the code does not use the information provided by those files.

**Comment by muhanzhang** [comment]
Hi, actually the files you deleted are the original files from the Dortmund graph database. To let DGCNN use them, we need to first run the "dortmund2txt.m" in MATLAB. Then, the "Synthie.txt" will be generated and other files are no longer useful.
