### ISSUE TITLE
Segmentation Fault error on windows10

### ISSUE THREAD

**Issue by hazelnutsgz** [muhanzhang/pytorch_DGCNN#13]
When running the "python main.py", it would produced segmentation fault error.

**Comment by muhanzhang** [comment]
Hi, sorry I didn't test SEAL on windows system. Can you successfully run other pytorch programs in windows 10, or is it only SEAL that cannot be ran?

**Comment by hazelnutsgz** [comment]
Thanks for your reply. The pure PyTorch program is runnable on my environment. 
And I used **make** as well as **g++** in Cgywin to compile the DLL, I was wondering whether it should be blamed to Cgywin. 
Furthermore, could you please provide the specific version of platform(eg. OS)&toolchain(eg. g++) to set up the project? Thanks.

**Comment by muhanzhang** [comment]
Hi, I use 
Linux version 3.10.0-514.21.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ).

**Comment by hazelnutsgz** [comment]
Thanks for your info~
