### ISSUE TITLE
How to convert to multilabel classifier

### ISSUE THREAD

**Issue by matgreco** [muhanzhang/pytorch_DGCNN#16]
Hello,

How can i convert the code for multilevel graphs classifier?

Thank's-

**Comment by veophi** [comment]
> Hello,
> 
> How can i convert the code for multilevel graphs classifier?
> 
> Thank's-

I think you just replace the last dense layer with multilabel classifier.

**Comment by matgreco** [comment]
> > Hello,
> > How can i convert the code for multilevel graphs classifier?
> > Thank's-
> 
> I think you just replace the last dense layer with multilabel classifier.

Sure! thank's.

But the project, into his mlp file include a function to make regresions.

How can i use it?

**Comment by muhanzhang** [comment]
See #23
