### ISSUE TITLE
I have a little question about the code

### ISSUE THREAD

**Issue by OceanTangWei** [muhanzhang/pytorch_DGCNN#18]
in DGCNN_embedding.py  line38，it seems that you set the kernel size as 0，does it make any sense ?

**Comment by muhanzhang** [comment]
Hi, in line 31, I have set it to "conv1d_kws[0] = self.total_latent_dim". The 0 is only a placeholder, as I will modify it later anyway. Thanks.

**Comment by OceanTangWei** [comment]
Thanks a lot~~~
