### ISSUE TITLE
.mat files

### ISSUE THREAD

**Issue by LYF14020510036** [muhanzhang/pytorch_DGCNN#20]
Hello, I am a beginner of graph classification task. Could you tell me where is the code used to generate .mat files in folder data?  If my graph benchmark datasets are downloaded from https://ls11-www.cs.tu-dortmund.de/staff/morris/graphkerneldatasets, do I need only the dortmund2txt.m file instead of the mat2txt.m file?

**Comment by muhanzhang** [comment]
Yes. The .mat files are following the WL kernel toolbox tradition, and are rarely used by graph neural networks. If you use dortmund datasets, you only need "dortmund2txt.m". All graph datasets used here are in txt formats.

**Comment by LYF14020510036** [comment]
感谢您的回复，我注意到所用的数据集中原始的 **_graph_labels.txt 中 相同的lable 是在一块的（图1），如果label 是无序的（图2），是不是不支持
![image](https://user-images.githubusercontent.com/30076500/64308563-463a1380-cfcc-11e9-82ca-b74392fffe98.png)
![image](https://user-images.githubusercontent.com/30076500/64308599-5eaa2e00-cfcc-11e9-9cbd-e396b45df44a.png)

**Comment by muhanzhang** [comment]
并不需要labels有序。dortmund2txt.m 会自动处理成最终的txt格式。

**Comment by LYF14020510036** [comment]
感谢您的回复，对我很多帮助，想入坑图分类，节点分类，您的work很赞,  非常感谢开源您的code,  我尝试调试您的代码

**Comment by LYF14020510036** [comment]
不好意思，又麻烦你了， 当我使用 dortmund2txt.m 转换数据集 COLLAB 时，报错，  你有遇到过不
![image](https://user-images.githubusercontent.com/30076500/64310500-daa77480-cfd2-11e9-8174-cb401d7e6ccc.png)

**Comment by muhanzhang** [comment]
Hi, please try to "clear all" before processing a new dataset.

**Comment by LYF14020510036** [comment]
非常感谢您的指导， 真的解决了
