### ISSUE TITLE
About node feature

### ISSUE THREAD

**Issue by Mrslock** [muhanzhang/pytorch_DGCNN#21]
Hi, thanks for the amazing work. I have a question, as far as I know, In ENZYMES, every node in every graph has features, but in your 'proteins.txt', you seemed to only use node label, I donnot know why.

**Comment by muhanzhang** [comment]
Hi, thanks for the question. The proteins dataset I used is a simplified one without continuous node attributes. You may download the [proteins_full](https://ls11-www.cs.tu-dortmund.de/people/morris/graphkerneldatasets/PROTEINS_full.zip) and use my "dortmund2txt.m" MATLAB script to generate the full dataset with continuous node attributes.

**Comment by Mrslock** [comment]
But I mean, if node attributes are not used in graph classification, will the result be not good enough? Can this code run with considering node attributes?

**Comment by muhanzhang** [comment]
Probably, the results won't be as good as using node attributes. This code can certainly run with considering node attributes.

**Comment by Mrslock** [comment]
I see, Thanks a lot！
