### ISSUE TITLE
 Compile  about  C  ++

### ISSUE THREAD

**Issue by LiQiu1234** [muhanzhang/pytorch_DGCNN#22]
Hello my env is python 3.6 with pytorch 1.0. So i  can nt  use your  32 bits  files which was compiled by c++ files. Can you provide 64 bits files that are recompiled? Thank you!

**Comment by muhanzhang** [comment]
Hi, have you tried to type "make -j4" in your command line to compile the C++ files yourself? I cannot provide you compiled files as those compiled on my machine won't work on yours.
