### ISSUE TITLE
Is it possible to use this pipeline with Dataset more than 2 classes? And how to do that?

### ISSUE THREAD

**Issue by DL8614** [muhanzhang/pytorch_DGCNN#23]

**Comment by DL8614** [comment]
I have dataset with more than 2 classes and I can prepare according to discription of 'How to use own Dataset'. But what should I change so I can use it for multi label dataset?

**Comment by muhanzhang** [comment]
Hi, multi-class dataset is supported by DGCNN. There is no need to change. For example, the ENZYMES dataset has 6 classes. Thanks!

**Comment by DL8614** [comment]
yes, It works. I can train the network on my dataset. Thanks. Morever, if I want to train the network with the features for every node, for example I have one dimensional feature called confidence score for every node, where should I add these features in Dataset, so that network can consider also features of node during training? You explained one time to use dortmund2txt.m but I cannot figure out, that How can I add to my own dataset?

**Comment by muhanzhang** [comment]
Hi, if your node feature is only integer labels, you can follow the README under data/ to transform your dataset to a txt file. If you have additional continuous feature, you can append it to each line (representing a node) of the txt file. Check "data/Synthie/Synthie.txt" for the format.
