### ISSUE TITLE
How to install in windows?

### ISSUE THREAD

**Issue by sherringzhang** [muhanzhang/pytorch_DGCNN#27]
I want to run in windows env. how to do install?

**Comment by muhanzhang** [comment]
Hi, I have tried several solutions. The best way to run it on windows is to install the linux sub-system in win10. Please follow this [link](https://docs.microsoft.com/en-us/windows/wsl/install-win10) to install ubuntu on win10. Then, you can just use command lines to install and run python like normal. 

Several notes include: 1) The installed ubuntu is a minimum version, where you have to install make/pip3/pytorch etc. by your self. Fortunately, they all have good prompts. 2) Remember to make several changes to "run_DGCNN.sh", such as the "gpu_or_cpu" option according to whether your installed pytorch is gpu-enabled or not (my win10 laptop does not have a gpu). 

Let me know whether you can successfully run it on windows.

**Comment by sherringzhang** [comment]
Thanks for kindly reply. I install minGW and util-linux-ng in windows but still can't compile C++ . Finally i config pycharm to remote run on another linux server and it successed.
