### ISSUE TITLE
invalid ELF header?

### ISSUE THREAD

**Issue by polyguo** [muhanzhang/pytorch_DGCNN#3]
while in the pytorch_DGCNN directory i ran `git clone https://github.com/Hanjun-Dai/pytorch_structure2vec` and ran `make -j4` while in `./s2v_lib/` i then moved all the contents of `pytorch_structure2vec` into `pytorch_DGCNN` since `main.py` expects `s2v.py` to be in the same directory.
when running i get the following error

```
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from DGCNN_embedding import DGCNN
  File "/vagrant/DGCNN_embedding.py", line 16, in <module>
    from s2v_lib import S2VLIB
  File "/vagrant/s2v_lib.py", line 127, in <module>
    S2VLIB = _s2v_lib(sys.argv)
  File "/vagrant/s2v_lib.py", line 11, in __init__
    self.lib = ctypes.CDLL('%s/build/dll/libs2v.so' % dir_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /vagrant/build/dll/libs2v.so: invalid ELF header
```

**Comment by muhanzhang** [comment]
Hi! Please do not move the contents of `pytorch_structure2vec/` to the root folder. Please compile `pytorch_structure2vec` separately inside its own folder. The `main.py` will add the `s2v_lib/` in `pytorch_structure2vec` to the system path.

**Comment by polyguo** [comment]
I followed the instructions as written, and i ran into this problem:

```
Initializing DGCNN
  0%|          | 0/21 [00:00<?, ?batch/s]Traceback (most recent call last):
  File "main.py", line 187, in <module>
    avg_loss = loop_dataset(train_graphs, classifier, train_idxes, optimizer=optimizer)
  File "main.py", line 131, in loop_dataset
    logits, loss, acc = classifier(batch_graph)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "main.py", line 107, in forward
    embed = self.s2v(batch_graph, node_feat, None)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/om2/user/poliguo/dgcnn/DGCNN_embedding.py", line 56, in forward
    n2n_sp, e2n_sp, subg_sp = S2VLIB.PrepareMeanField(graph_list)
AttributeError: 'NoneType' object has no attribute 'PrepareMeanField'
Exception KeyError: KeyError(<weakref at 0x2b2dbf56f3c0; to 'tqdm' at 0x2b2dbf166190>,) in <bound method tqdm.__del__ of   0%|          | 0/21 [00:00<?, ?batch/s]> ignored
```

which i believe is because the `if os.path.exists(dll_path):` clause in `s2v_lib.py` is failing for some reason. i've checked and the `.so` file is definitely there.

**Comment by muhanzhang** [comment]
Hi! Can you try to completely reinstall the software again?

**Comment by polyguo** [comment]
I completely deleted the directory and did the whole thing over. I get the exact same error.
Do you have any suggestions as to where i should be looking?

**Comment by muhanzhang** [comment]
Got it. There is something changed in the git version of the pytorch_structure2vec so that S2VLIB cannot be initialized. Please use the `pytorch_structure2vec-master.zip` version instead and then it should work.

**Comment by fs302** [comment]
Hi muhan, I got the same problem with polyguo while deploy DGCNN to cloud. Actually, I can run it locally but when deploy online, the .so file raise the error. I do recommend to make DGCNN independent to avoid such problem, which could help this algorithm got larger population.

**Comment by muhanzhang** [comment]
Sorry for the late reply. Did you solve the .so issue for online deployment later by using the included _pytorch_structure2vec-master.zip_? I'd like to know the possible reasons. Thank you for the suggestion to make it independent too. I'll consider that.

**Comment by muhanzhang** [comment]
> Hi muhan, I got the same problem with polyguo while deploy DGCNN to cloud. Actually, I can run it locally but when deploy online, the .so file raise the error. I do recommend to make DGCNN independent to avoid such problem, which could help this algorithm got larger population.

Just cleaned the code. Now it is independent from structure2vec.
