### ISSUE TITLE
libgnn shared object library

### ISSUE THREAD

**Issue by tsKenneth** [muhanzhang/pytorch_DGCNN#30]
Hi, may I ask about the motivation behind writing libgnn in C (i.e. better performance)? Is it possible for me to implement it entirely in python? I am thinking of implementing it entirely in networkx to remove the dependence on the shared object library.

Thank you!

**Comment by muhanzhang** [comment]
Hi, the backend is based on Hanjun Dai's [structure2vec](https://github.com/Hanjun-Dai/pytorch_structure2vec). It shows faster graph neural network training speed from my experience than pure python-based approaches. You can of course implement it based on networkx and pytorch only, but you may see efficiency drops.

**Comment by tsKenneth** [comment]
Thank you for clarifying!
