### ISSUE TITLE
What is the tag if node?

### ISSUE THREAD

**Issue by jingcaiguo** [muhanzhang/pytorch_DGCNN#31]
Hi,
I read your data format description:

"the i-th line describes the information of ith node (0 based), which starts with t m, where t is the tag of current node, and m is the number of neighbors of current node",

Can you explain what is the tag of node ?

**Comment by muhanzhang** [comment]
Hi, the tag of a node is an integer label, marking the node's class. For example, in bioinformatics datasets, a molecule graph's node label can represent this node's atom number. They are typically transformed to one-hot encodings before feeding into a GNN.

**Comment by jingcaiguo** [comment]
> Hi, the tag of a node is an integer label, marking the node's class. For example, in bioinformatics datasets, a molecule graph's node label can represent this node's atom number. They are typically transformed to one-hot encodings before feeding into a GNN.

Thanks for your answer!
I have checked your code for converting .mat to .txt, based on my understanding, the node tag should be set to all zero if we do not care about the node classification, right ?

**Comment by muhanzhang** [comment]
No. In all graph classification tasks, we do not care about node classification. But we still can leverage node labels to better classify whole graphs. These node labels can serve as initial node features fed to a GNN (instead of the ground-truth labels used in semi-supervised node classification).

**Comment by jingcaiguo** [comment]
> No. In all graph classification tasks, we do not care about node classification. But we still can leverage node labels to better classify whole graphs. These node labels can serve as initial node features fed to a GNN (instead of the ground-truth labels used in semi-supervised node classification).

Say we have the graph-level labels and node-level features (e.g., multi dimensional vectors), each node label is not available or not sensitive, and we only care about the graph-level classification, then can we just set all node tags to zero in the processed txt input data?

**Comment by jingcaiguo** [comment]
> No. In all graph classification tasks, we do not care about node classification. But we still can leverage node labels to better classify whole graphs. These node labels can serve as initial node features fed to a GNN (instead of the ground-truth labels used in semi-supervised node classification).

If the nodes have mutil-dimentional features, then the initial node features are these features. Thus, can we say the node tag is useless and can be set to all zero?

**Comment by muhanzhang** [comment]
> > No. In all graph classification tasks, we do not care about node classification. But we still can leverage node labels to better classify whole graphs. These node labels can serve as initial node features fed to a GNN (instead of the ground-truth labels used in semi-supervised node classification).
> 
> If the nodes have mutil-dimentional features, then the initial node features are these features. Thus, can we say the node tag is useless and can be set to all zero?

No. Multi-dimensional features and node tags are both useful for graph classification. We can concatenate them as initial input features.

**Comment by tyua321** [comment]
> > > No. In all graph classification tasks, we do not care about node classification. But we still can leverage node labels to better classify whole graphs. These node labels can serve as initial node features fed to a GNN (instead of the ground-truth labels used in semi-supervised node classification).
> > 
> > 
> > If the nodes have mutil-dimentional features, then the initial node features are these features. Thus, can we say the node tag is useless and can be set to all zero?
> 
> No. Multi-dimensional features and node tags are both useful for graph classification. We can concatenate them as initial input features.


So how to deal with the dataset where there is no "node tag" but only node continuous features?

**Comment by muhanzhang** [comment]
Just give all nodes the same node tag 0, or use node degrees as node tags.

**Comment by jingcaiguo** [comment]
Thank you, Muhan.
