### ISSUE TITLE
questions about social network datasets

### ISSUE THREAD

**Issue by Tansy-Tansy** [muhanzhang/pytorch_DGCNN#35]
Hi，I'm reading your paper nowadays and confused about social network datasets.
Taking IMDB as an example, I want to know what a input graph and nodes (of it) denote respectively. 
I think each input graph denotes a movie review, and nodes in the graph represent words in the corresponding text respectively.And edges represent word co-occurrence information, depending on the size of window sliding. 
If so, what is X(inital node input feature)? 
If I get it wrong, then what does they denote?
Can you help me answer these questions? Thank you very much!

**Comment by muhanzhang** [comment]
Hi! IMDB-B is a movie collaboration dataset where ego-networks for actors/actresses are
classified into Action or Romance genres. IMDB-M is a multi-class version of IMDB-B containing genres Comedy, Romance, and Sci-Fi. See [1]. There are no node features. X is initialized with all-1 vectors.

[1] P.  Yanardag  and  S.  Vishwanathan, “Deep  graph  kernels, ”  in  “Proceedings  of  the  21th  ACM  SIGKDD  International  Conference  on  Knowledge Discovery  and  Data  Mining, ”  (ACM, 2015), pp.  1365–1374.
