### ISSUE TITLE
Suffling dataset

### ISSUE THREAD

**Issue by andreitam11** [muhanzhang/pytorch_DGCNN#41]
Hello. Is there a way to shuffle the dataset? I have the graphs in the .txt, but unfortunately, the similarly labeled graphs are grouped together. Is there a way to shuffle them before running?

**Comment by muhanzhang** [comment]
Yes. You can randomly shuffle the `train_graphs` after [loading them from txt](https://github.com/muhanzhang/pytorch_DGCNN/blob/50f504131ca66382f3f078ae98e59aa3ae35b795/main.py#L197) by 

    random.shuffle(train_graphs)
