### ISSUE TITLE
Run with error

### ISSUE THREAD

**Issue by bearinsuke** [muhanzhang/pytorch_DGCNN#43]
Hi,
Thanks for the contribution.
I have a problem when importing the compiled dgnn. When reading libgnn.so the error: OSError: "[WinError 126] The specified module could not be found" was raised.

Thanks,

**Comment by muhanzhang** [comment]
Hi, did you use windows? The repo does not support windows well. See #36.

**Comment by bearinsuke** [comment]
Hi,
Thanks for reminding me. I actually use both Win10 and Ubuntu systems to handle this. It is needed another way to compile the C files and it does work in some pc with windows systems. Anyway, thanks for helping!
