### ISSUE TITLE
load_data

### ISSUE THREAD

**Issue by wxfsd** [muhanzhang/pytorch_DGCNN#9]
with open('data/%s/%s.txt' % (cmd_args.data, cmd_args.data), 'r') as f:
        n_g = int(f.readline().strip())
        for i in range(n_g):
            row = f.readline().strip().split()
            n, l = [int(w) for w in row]   ???? 一行数据如果多于两个值，就无法赋值了啊？报错，为什么啊

row = [0,1,7]
ValueError: too many values to unpack (expected 2)

**Comment by muhanzhang** [comment]
Hi, the data format is to use the first line of each graph block to indicate n (number of nodes in the graph) and l (the graph class). So it should have exactly two values in this line. Check https://github.com/muhanzhang/pytorch_DGCNN/tree/master/data/README.md for more details.
